# Generated by Django 5.0.7 on 2024-07-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gogreenapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pic')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=50)),
                ('spec', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Items',
        ),
    ]
